---
# build os/arch for gox
build:
  # - darwin/386
  - darwin/amd64
  - linux/386
  - linux/amd64
  - linux/arm
  - windows/amd64
  - freebsd/amd64
target: ovh-cli
releases:
  # yaml keys must match the git tag
  v0.1:
    name: "ovh-cli for shell v0.1"
    description: |
      This is our first draft release.

      introduce:
        - stdin + argument parsing
        - low tested
  v0.2:
    name: "ovh-cli for shell v0.2 alpha"
    description: |
      OVH cli for OVH api for command line shell.

      Changes:
        - This fix JSON_INPUT read fail
        - remove darwin/386 add freebsd/amd64 binaries
        - remove symbols from binaries (-s -w)

      Introduce:
        - first bats test
